name: Build

on:
  push:
    branches: 
      - master
      - actions
      - ci
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --verbosity normal
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | cut -c 2-)
    - name: Pack
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet pack -p:PackageVersion=${{ steps.get_version.outputs.VERSION }}
