name: Build

on:
  push:
    branches: 
      - master
      - actions
      - ci
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --verbosity normal
    - name: Get tag version
      id: getTagVersion
      run: |
        echo ::set-output name=TAGVERSION::${GITHUB_REF/refs\/tags\//}
        unset ISTAG
        if [ -n $TAGVERSION ]; then ISTAG='true' ; fi
        echo ::set-output name=ISTAG::${ISTAG}
      
    - name: Push
      if: steps.getTagVersion.output.ISTAG
      run: dotnet pack -p:PackageVersion=$VERSION
