name: Build Pipeline

on:
  release:
    types: [published]
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      run: dotnet build -c Release

    - name: Test
      run: dotnet test -v normal

    - name: Pack
      if: ${{ github.event_name == 'release' }}
      run: dotnet pack -c Release -o nuget-output -p:Version=${{ github.event.release.tag_name }}

    - name: Push
      if: ${{ github.event_name == 'release' }}
      run: dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} nuget-output/**/*.nupkg
